sudo: false

language: java

matrix:
  include:
  - jdk: oraclejdk8
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.0.7
  - jdk: oraclejdk8
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.1.2-4
  - jdk: oraclejdk8
    env: TERM=dumb KOTLIN_VERSION=1.0.7
  - jdk: oraclejdk8
    env: TERM=dumb KOTLIN_VERSION=1.1.2-4


env:
  matrix:
  - TERM=dumb

install:
 - true

script:
  - ./gradlew test

notifications:
  email: false